// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: dockyard.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DockyardService_StreamCommunication_FullMethodName = "/pb.DockyardService/StreamCommunication"
)

// DockyardServiceClient is the client API for DockyardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockyardServiceClient interface {
	StreamCommunication(ctx context.Context, opts ...grpc.CallOption) (DockyardService_StreamCommunicationClient, error)
}

type dockyardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockyardServiceClient(cc grpc.ClientConnInterface) DockyardServiceClient {
	return &dockyardServiceClient{cc}
}

func (c *dockyardServiceClient) StreamCommunication(ctx context.Context, opts ...grpc.CallOption) (DockyardService_StreamCommunicationClient, error) {
	stream, err := c.cc.NewStream(ctx, &DockyardService_ServiceDesc.Streams[0], DockyardService_StreamCommunication_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &dockyardServiceStreamCommunicationClient{stream}
	return x, nil
}

type DockyardService_StreamCommunicationClient interface {
	Send(*WorkerMessage) error
	Recv() (*ControlMessage, error)
	grpc.ClientStream
}

type dockyardServiceStreamCommunicationClient struct {
	grpc.ClientStream
}

func (x *dockyardServiceStreamCommunicationClient) Send(m *WorkerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dockyardServiceStreamCommunicationClient) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DockyardServiceServer is the server API for DockyardService service.
// All implementations must embed UnimplementedDockyardServiceServer
// for forward compatibility
type DockyardServiceServer interface {
	StreamCommunication(DockyardService_StreamCommunicationServer) error
	mustEmbedUnimplementedDockyardServiceServer()
}

// UnimplementedDockyardServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDockyardServiceServer struct {
}

func (UnimplementedDockyardServiceServer) StreamCommunication(DockyardService_StreamCommunicationServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCommunication not implemented")
}
func (UnimplementedDockyardServiceServer) mustEmbedUnimplementedDockyardServiceServer() {}

// UnsafeDockyardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockyardServiceServer will
// result in compilation errors.
type UnsafeDockyardServiceServer interface {
	mustEmbedUnimplementedDockyardServiceServer()
}

func RegisterDockyardServiceServer(s grpc.ServiceRegistrar, srv DockyardServiceServer) {
	s.RegisterService(&DockyardService_ServiceDesc, srv)
}

func _DockyardService_StreamCommunication_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DockyardServiceServer).StreamCommunication(&dockyardServiceStreamCommunicationServer{stream})
}

type DockyardService_StreamCommunicationServer interface {
	Send(*ControlMessage) error
	Recv() (*WorkerMessage, error)
	grpc.ServerStream
}

type dockyardServiceStreamCommunicationServer struct {
	grpc.ServerStream
}

func (x *dockyardServiceStreamCommunicationServer) Send(m *ControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dockyardServiceStreamCommunicationServer) Recv() (*WorkerMessage, error) {
	m := new(WorkerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DockyardService_ServiceDesc is the grpc.ServiceDesc for DockyardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockyardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DockyardService",
	HandlerType: (*DockyardServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCommunication",
			Handler:       _DockyardService_StreamCommunication_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dockyard.proto",
}
