// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: dockyard.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockyardService_StreamCommunication_FullMethodName = "/pb.DockyardService/StreamCommunication"
)

// DockyardServiceClient is the client API for DockyardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockyardServiceClient interface {
	StreamCommunication(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ControlMessage], error)
}

type dockyardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockyardServiceClient(cc grpc.ClientConnInterface) DockyardServiceClient {
	return &dockyardServiceClient{cc}
}

func (c *dockyardServiceClient) StreamCommunication(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DockyardService_ServiceDesc.Streams[0], DockyardService_StreamCommunication_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockyardService_StreamCommunicationClient = grpc.BidiStreamingClient[WorkerMessage, ControlMessage]

// DockyardServiceServer is the server API for DockyardService service.
// All implementations must embed UnimplementedDockyardServiceServer
// for forward compatibility.
type DockyardServiceServer interface {
	StreamCommunication(grpc.BidiStreamingServer[WorkerMessage, ControlMessage]) error
	mustEmbedUnimplementedDockyardServiceServer()
}

// UnimplementedDockyardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockyardServiceServer struct{}

func (UnimplementedDockyardServiceServer) StreamCommunication(grpc.BidiStreamingServer[WorkerMessage, ControlMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamCommunication not implemented")
}
func (UnimplementedDockyardServiceServer) mustEmbedUnimplementedDockyardServiceServer() {}
func (UnimplementedDockyardServiceServer) testEmbeddedByValue()                         {}

// UnsafeDockyardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockyardServiceServer will
// result in compilation errors.
type UnsafeDockyardServiceServer interface {
	mustEmbedUnimplementedDockyardServiceServer()
}

func RegisterDockyardServiceServer(s grpc.ServiceRegistrar, srv DockyardServiceServer) {
	// If the following call pancis, it indicates UnimplementedDockyardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockyardService_ServiceDesc, srv)
}

func _DockyardService_StreamCommunication_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DockyardServiceServer).StreamCommunication(&grpc.GenericServerStream[WorkerMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockyardService_StreamCommunicationServer = grpc.BidiStreamingServer[WorkerMessage, ControlMessage]

// DockyardService_ServiceDesc is the grpc.ServiceDesc for DockyardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockyardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DockyardService",
	HandlerType: (*DockyardServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCommunication",
			Handler:       _DockyardService_StreamCommunication_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dockyard.proto",
}
